### ISSUE TITLE
When is the new version going to come out

### ISSUE THREAD

**Issue by brow419** [DavidMoore/ipfilter#16]
Just wondering when you will have a new version out that will hopefully pickup on that i have a bittorrent.

**Comment by DavidMoore** [comment]
Hi. To be honest, I'm not sure. It seems impossible to find a reliable, up to date list source, which means there's no real value to the filter anymore. I'll push out the new version within the month and go from there.

**Comment by brow419** [comment]
are you going to be pushing out they new version anytime soon?

**Comment by madhouserevival** [comment]
http://ip2k.com/list.gz Is said to be updated daily. Came looking here because your program is still downloading a list from Aug 16.Hopefully that list will help.

**Comment by DavidMoore** [comment]
Thanks @madhouserevival , I'll take a look.
I should have a full update of the app when I'm back from holiday in October, but possibly before (I can't make a promise on September).

**Comment by madhouserevival** [comment]
Thanks, Dave. I haven't had a warning about illegal torrents since 2007
(made the mistake of enabling DHT). I always keep my filter updated just in
case. It's incredibly nice that someone like you goes through the trouble
of keeping that possible. :)

On Tue, Sep 15, 2015 at 3:37 AM, David Moore <notifications@github.com>
wrote:

> Thanks @madhouserevival <https://github.com/madhouserevival> , I'll take
> a look.
> I should have a full update of the app when I'm back from holiday in
> October, but possibly before (I can't make a promise on September).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DavidMoore/ipfilter/issues/16#issuecomment-140349433>.
>



-- 
SaveTheChildren.org

**Comment by DavidMoore** [comment]
I've pushed 2.0.0.5 live with a few fixes, including the BitTorrent / uTorrent detection fix (#10)

**Comment by JonnyRedHed** [comment]
Keep up the good work David.  You still have a lot of users who respect what you do here.

**Comment by JonnyRedHed** [comment]
There is this forum thread here:

http://www.nsaneforums.com/topic/55959-ip-filter-downloader/?page=17

Does this help in your quest for quality lists?

**Comment by madhouserevival** [comment]
File was deleted. Anyway, I found Exil Ipfilter Updater does what the
old ipfilter updater did but with the bonus of applying to mulitple
programs not just Utorrent. But thanks for the update.

On 3/24/16, JonnyRedHed <notifications@github.com> wrote:
> There is this forum thread here:
>
> http://www.nsaneforums.com/topic/55959-ip-filter-downloader/?page=17
>
> Does this help in your quest for quality lists?
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/DavidMoore/ipfilter/issues/16#issuecomment-200999607


-- 
SaveTheChildren.org

**Comment by JonnyRedHed** [comment]
I find this one by David to be perfect, it updates utorrent 3.2.1 and Qbitorrent just fine.   

I don't know much about ip filter lists.  I'm not keen on registering and paying a subscription for them I know that.

**Comment by DavidMoore** [comment]
Hi. Version 2.1 is out now, mainly with a new update / installer.

I've updated the launch page to note that uTorrent, BitTorrent and qBitTorrent are supported out of the box.

There'll be a few new improvements coming in the next week or two, including ironing out any problems in the upgrade process.

Then I'll focus on nailing down the actual list sources and quality.

**Comment by JonnyRedHed** [comment]
Hi David,

Thanks for the update.  Keep up the good work.

Regards
Jonny
